//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// PostAuthOtpJSONBody defines parameters for PostAuthOtp.
type PostAuthOtpJSONBody struct {
	// Email Email address of the user
	Email string `json:"email"`
}

// PostAuthOtpVerifyJSONBody defines parameters for PostAuthOtpVerify.
type PostAuthOtpVerifyJSONBody struct {
	// Email Email address of the user
	Email string `json:"email"`

	// OtpCode OTP code received via email
	OtpCode string `json:"otpCode"`
}

// PostAuthOtpJSONRequestBody defines body for PostAuthOtp for application/json ContentType.
type PostAuthOtpJSONRequestBody PostAuthOtpJSONBody

// PostAuthOtpVerifyJSONRequestBody defines body for PostAuthOtpVerify for application/json ContentType.
type PostAuthOtpVerifyJSONRequestBody PostAuthOtpVerifyJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostAuthOtpWithBody request with any body
	PostAuthOtpWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAuthOtp(ctx context.Context, body PostAuthOtpJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAuthOtpVerifyWithBody request with any body
	PostAuthOtpVerifyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAuthOtpVerify(ctx context.Context, body PostAuthOtpVerifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostAuthOtpWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAuthOtpRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAuthOtp(ctx context.Context, body PostAuthOtpJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAuthOtpRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAuthOtpVerifyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAuthOtpVerifyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAuthOtpVerify(ctx context.Context, body PostAuthOtpVerifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAuthOtpVerifyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostAuthOtpRequest calls the generic PostAuthOtp builder with application/json body
func NewPostAuthOtpRequest(server string, body PostAuthOtpJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAuthOtpRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAuthOtpRequestWithBody generates requests for PostAuthOtp with any type of body
func NewPostAuthOtpRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/otp")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAuthOtpVerifyRequest calls the generic PostAuthOtpVerify builder with application/json body
func NewPostAuthOtpVerifyRequest(server string, body PostAuthOtpVerifyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAuthOtpVerifyRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAuthOtpVerifyRequestWithBody generates requests for PostAuthOtpVerify with any type of body
func NewPostAuthOtpVerifyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/otp-verify")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostAuthOtpWithBodyWithResponse request with any body
	PostAuthOtpWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAuthOtpResponse, error)

	PostAuthOtpWithResponse(ctx context.Context, body PostAuthOtpJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAuthOtpResponse, error)

	// PostAuthOtpVerifyWithBodyWithResponse request with any body
	PostAuthOtpVerifyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAuthOtpVerifyResponse, error)

	PostAuthOtpVerifyWithResponse(ctx context.Context, body PostAuthOtpVerifyJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAuthOtpVerifyResponse, error)
}

type PostAuthOtpResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			// IsNewUser Indicates if this is a new user registration
			IsNewUser *bool `json:"isNewUser,omitempty"`
		} `json:"data,omitempty"`

		// Message Message from the API call
		Message *string `json:"message,omitempty"`

		// Success Success status of the API call
		Success *bool `json:"success,omitempty"`

		// Timestamp Timestamp of the response
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON400 *struct {
		// Error Error object
		Error *struct {
			// Code Error code
			Code *string `json:"code,omitempty"`

			// Message Error message
			Message *string `json:"message,omitempty"`

			// Trace Error stack trace for debugging
			Trace *string `json:"trace,omitempty"`
		} `json:"error,omitempty"`

		// Message Message from the API call
		Message *string `json:"message,omitempty"`

		// Success Success status of the API call
		Success *bool `json:"success,omitempty"`

		// Timestamp Timestamp of the response
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON500 *struct {
		// Error Error object
		Error *struct {
			// Code Error code
			Code *string `json:"code,omitempty"`

			// Message Error message
			Message *string `json:"message,omitempty"`

			// Trace Error stack trace for debugging
			Trace *string `json:"trace,omitempty"`
		} `json:"error,omitempty"`

		// Message Message from the API call
		Message *string `json:"message,omitempty"`

		// Success Success status of the API call
		Success *bool `json:"success,omitempty"`

		// Timestamp Timestamp of the response
		Timestamp *string `json:"timestamp,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostAuthOtpResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAuthOtpResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAuthOtpVerifyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			// AccessToken Access token for the user
			AccessToken *string `json:"accessToken,omitempty"`

			// RefreshToken Refresh token for the user
			RefreshToken *string `json:"refreshToken,omitempty"`
		} `json:"data,omitempty"`

		// Message Message from the API call
		Message *string `json:"message,omitempty"`

		// Success Success status of the API call
		Success *bool `json:"success,omitempty"`

		// Timestamp Timestamp of the response
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON400 *struct {
		// Error Error object
		Error *struct {
			// Code Error code
			Code *string `json:"code,omitempty"`

			// Message Error message
			Message *string `json:"message,omitempty"`

			// Trace Error stack trace for debugging
			Trace *string `json:"trace,omitempty"`
		} `json:"error,omitempty"`

		// Message Message from the API call
		Message *string `json:"message,omitempty"`

		// Success Success status of the API call
		Success *bool `json:"success,omitempty"`

		// Timestamp Timestamp of the response
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON500 *struct {
		// Error Error object
		Error *struct {
			// Code Error code
			Code *string `json:"code,omitempty"`

			// Message Error message
			Message *string `json:"message,omitempty"`

			// Trace Error stack trace for debugging
			Trace *string `json:"trace,omitempty"`
		} `json:"error,omitempty"`

		// Message Message from the API call
		Message *string `json:"message,omitempty"`

		// Success Success status of the API call
		Success *bool `json:"success,omitempty"`

		// Timestamp Timestamp of the response
		Timestamp *string `json:"timestamp,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostAuthOtpVerifyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAuthOtpVerifyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostAuthOtpWithBodyWithResponse request with arbitrary body returning *PostAuthOtpResponse
func (c *ClientWithResponses) PostAuthOtpWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAuthOtpResponse, error) {
	rsp, err := c.PostAuthOtpWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAuthOtpResponse(rsp)
}

func (c *ClientWithResponses) PostAuthOtpWithResponse(ctx context.Context, body PostAuthOtpJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAuthOtpResponse, error) {
	rsp, err := c.PostAuthOtp(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAuthOtpResponse(rsp)
}

// PostAuthOtpVerifyWithBodyWithResponse request with arbitrary body returning *PostAuthOtpVerifyResponse
func (c *ClientWithResponses) PostAuthOtpVerifyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAuthOtpVerifyResponse, error) {
	rsp, err := c.PostAuthOtpVerifyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAuthOtpVerifyResponse(rsp)
}

func (c *ClientWithResponses) PostAuthOtpVerifyWithResponse(ctx context.Context, body PostAuthOtpVerifyJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAuthOtpVerifyResponse, error) {
	rsp, err := c.PostAuthOtpVerify(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAuthOtpVerifyResponse(rsp)
}

// ParsePostAuthOtpResponse parses an HTTP response from a PostAuthOtpWithResponse call
func ParsePostAuthOtpResponse(rsp *http.Response) (*PostAuthOtpResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAuthOtpResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				// IsNewUser Indicates if this is a new user registration
				IsNewUser *bool `json:"isNewUser,omitempty"`
			} `json:"data,omitempty"`

			// Message Message from the API call
			Message *string `json:"message,omitempty"`

			// Success Success status of the API call
			Success *bool `json:"success,omitempty"`

			// Timestamp Timestamp of the response
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Error Error object
			Error *struct {
				// Code Error code
				Code *string `json:"code,omitempty"`

				// Message Error message
				Message *string `json:"message,omitempty"`

				// Trace Error stack trace for debugging
				Trace *string `json:"trace,omitempty"`
			} `json:"error,omitempty"`

			// Message Message from the API call
			Message *string `json:"message,omitempty"`

			// Success Success status of the API call
			Success *bool `json:"success,omitempty"`

			// Timestamp Timestamp of the response
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Error Error object
			Error *struct {
				// Code Error code
				Code *string `json:"code,omitempty"`

				// Message Error message
				Message *string `json:"message,omitempty"`

				// Trace Error stack trace for debugging
				Trace *string `json:"trace,omitempty"`
			} `json:"error,omitempty"`

			// Message Message from the API call
			Message *string `json:"message,omitempty"`

			// Success Success status of the API call
			Success *bool `json:"success,omitempty"`

			// Timestamp Timestamp of the response
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAuthOtpVerifyResponse parses an HTTP response from a PostAuthOtpVerifyWithResponse call
func ParsePostAuthOtpVerifyResponse(rsp *http.Response) (*PostAuthOtpVerifyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAuthOtpVerifyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				// AccessToken Access token for the user
				AccessToken *string `json:"accessToken,omitempty"`

				// RefreshToken Refresh token for the user
				RefreshToken *string `json:"refreshToken,omitempty"`
			} `json:"data,omitempty"`

			// Message Message from the API call
			Message *string `json:"message,omitempty"`

			// Success Success status of the API call
			Success *bool `json:"success,omitempty"`

			// Timestamp Timestamp of the response
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Error Error object
			Error *struct {
				// Code Error code
				Code *string `json:"code,omitempty"`

				// Message Error message
				Message *string `json:"message,omitempty"`

				// Trace Error stack trace for debugging
				Trace *string `json:"trace,omitempty"`
			} `json:"error,omitempty"`

			// Message Message from the API call
			Message *string `json:"message,omitempty"`

			// Success Success status of the API call
			Success *bool `json:"success,omitempty"`

			// Timestamp Timestamp of the response
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Error Error object
			Error *struct {
				// Code Error code
				Code *string `json:"code,omitempty"`

				// Message Error message
				Message *string `json:"message,omitempty"`

				// Trace Error stack trace for debugging
				Trace *string `json:"trace,omitempty"`
			} `json:"error,omitempty"`

			// Message Message from the API call
			Message *string `json:"message,omitempty"`

			// Success Success status of the API call
			Success *bool `json:"success,omitempty"`

			// Timestamp Timestamp of the response
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send OTP code to email for existing users or create new user account
	// (POST /auth/otp)
	PostAuthOtp(w http.ResponseWriter, r *http.Request)
	// Verify OTP code
	// (POST /auth/otp-verify)
	PostAuthOtpVerify(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthOtp operation middleware
func (siw *ServerInterfaceWrapper) PostAuthOtp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthOtp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthOtpVerify operation middleware
func (siw *ServerInterfaceWrapper) PostAuthOtpVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthOtpVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth/otp", wrapper.PostAuthOtp)
	m.HandleFunc("POST "+options.BaseURL+"/auth/otp-verify", wrapper.PostAuthOtpVerify)

	return m
}

type PostAuthOtpRequestObject struct {
	Body *PostAuthOtpJSONRequestBody
}

type PostAuthOtpResponseObject interface {
	VisitPostAuthOtpResponse(w http.ResponseWriter) error
}

type PostAuthOtp200JSONResponse struct {
	Data *struct {
		// IsNewUser Indicates if this is a new user registration
		IsNewUser *bool `json:"isNewUser,omitempty"`
	} `json:"data,omitempty"`

	// Message Message from the API call
	Message *string `json:"message,omitempty"`

	// Success Success status of the API call
	Success *bool `json:"success,omitempty"`

	// Timestamp Timestamp of the response
	Timestamp *string `json:"timestamp,omitempty"`
}

func (response PostAuthOtp200JSONResponse) VisitPostAuthOtpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthOtp400JSONResponse struct {
	// Error Error object
	Error *struct {
		// Code Error code
		Code *string `json:"code,omitempty"`

		// Message Error message
		Message *string `json:"message,omitempty"`

		// Trace Error stack trace for debugging
		Trace *string `json:"trace,omitempty"`
	} `json:"error,omitempty"`

	// Message Message from the API call
	Message *string `json:"message,omitempty"`

	// Success Success status of the API call
	Success *bool `json:"success,omitempty"`

	// Timestamp Timestamp of the response
	Timestamp *string `json:"timestamp,omitempty"`
}

func (response PostAuthOtp400JSONResponse) VisitPostAuthOtpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthOtp500JSONResponse struct {
	// Error Error object
	Error *struct {
		// Code Error code
		Code *string `json:"code,omitempty"`

		// Message Error message
		Message *string `json:"message,omitempty"`

		// Trace Error stack trace for debugging
		Trace *string `json:"trace,omitempty"`
	} `json:"error,omitempty"`

	// Message Message from the API call
	Message *string `json:"message,omitempty"`

	// Success Success status of the API call
	Success *bool `json:"success,omitempty"`

	// Timestamp Timestamp of the response
	Timestamp *string `json:"timestamp,omitempty"`
}

func (response PostAuthOtp500JSONResponse) VisitPostAuthOtpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthOtpVerifyRequestObject struct {
	Body *PostAuthOtpVerifyJSONRequestBody
}

type PostAuthOtpVerifyResponseObject interface {
	VisitPostAuthOtpVerifyResponse(w http.ResponseWriter) error
}

type PostAuthOtpVerify200JSONResponse struct {
	Data *struct {
		// AccessToken Access token for the user
		AccessToken *string `json:"accessToken,omitempty"`

		// RefreshToken Refresh token for the user
		RefreshToken *string `json:"refreshToken,omitempty"`
	} `json:"data,omitempty"`

	// Message Message from the API call
	Message *string `json:"message,omitempty"`

	// Success Success status of the API call
	Success *bool `json:"success,omitempty"`

	// Timestamp Timestamp of the response
	Timestamp *string `json:"timestamp,omitempty"`
}

func (response PostAuthOtpVerify200JSONResponse) VisitPostAuthOtpVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthOtpVerify400JSONResponse struct {
	// Error Error object
	Error *struct {
		// Code Error code
		Code *string `json:"code,omitempty"`

		// Message Error message
		Message *string `json:"message,omitempty"`

		// Trace Error stack trace for debugging
		Trace *string `json:"trace,omitempty"`
	} `json:"error,omitempty"`

	// Message Message from the API call
	Message *string `json:"message,omitempty"`

	// Success Success status of the API call
	Success *bool `json:"success,omitempty"`

	// Timestamp Timestamp of the response
	Timestamp *string `json:"timestamp,omitempty"`
}

func (response PostAuthOtpVerify400JSONResponse) VisitPostAuthOtpVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthOtpVerify500JSONResponse struct {
	// Error Error object
	Error *struct {
		// Code Error code
		Code *string `json:"code,omitempty"`

		// Message Error message
		Message *string `json:"message,omitempty"`

		// Trace Error stack trace for debugging
		Trace *string `json:"trace,omitempty"`
	} `json:"error,omitempty"`

	// Message Message from the API call
	Message *string `json:"message,omitempty"`

	// Success Success status of the API call
	Success *bool `json:"success,omitempty"`

	// Timestamp Timestamp of the response
	Timestamp *string `json:"timestamp,omitempty"`
}

func (response PostAuthOtpVerify500JSONResponse) VisitPostAuthOtpVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Send OTP code to email for existing users or create new user account
	// (POST /auth/otp)
	PostAuthOtp(ctx context.Context, request PostAuthOtpRequestObject) (PostAuthOtpResponseObject, error)
	// Verify OTP code
	// (POST /auth/otp-verify)
	PostAuthOtpVerify(ctx context.Context, request PostAuthOtpVerifyRequestObject) (PostAuthOtpVerifyResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostAuthOtp operation middleware
func (sh *strictHandler) PostAuthOtp(w http.ResponseWriter, r *http.Request) {
	var request PostAuthOtpRequestObject

	var body PostAuthOtpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthOtp(ctx, request.(PostAuthOtpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthOtp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthOtpResponseObject); ok {
		if err := validResponse.VisitPostAuthOtpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthOtpVerify operation middleware
func (sh *strictHandler) PostAuthOtpVerify(w http.ResponseWriter, r *http.Request) {
	var request PostAuthOtpVerifyRequestObject

	var body PostAuthOtpVerifyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthOtpVerify(ctx, request.(PostAuthOtpVerifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthOtpVerify")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthOtpVerifyResponseObject); ok {
		if err := validResponse.VisitPostAuthOtpVerifyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
