# Default development overrides (compose.override.yml is automatically used)

services:
  postgres:
    ports:
      - "5435:5432"

  api:
    build:
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../:/app
      - /app/bin
    environment:
      - AIR_LIVE_RELOAD=${AIR_LIVE_RELOAD}
    command: air -c docker/.air.toml
    ports:
      - "3003:3003"
    stdin_open: true
    tty: true