# Default development overrides (compose.override.yml is automatically used)

services:
  postgres:
    ports:
      - "5435:5432"

  api:
    build:
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../:/app
      - /app/bin
    environment:
      - AIR_LIVE_RELOAD=${AIR_LIVE_RELOAD}
      - DATABASE_URL=${DATABASE_URL}
      - GO_ENV=${GO_ENV}
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - RESEND_KEY=${RESEND_KEY}
      - ISSUER=${ISSUER}
      - AUDIENCE=${AUDIENCE}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRE_TIME=${ACCESS_TOKEN_EXPIRE_TIME}
      - REFRESH_TOKEN_EXPIRE_TIME=${REFRESH_TOKEN_EXPIRE_TIME}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_URL=${R2_URL}
      - R2_TOKEN_VALUE=${R2_TOKEN_VALUE}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ACCESS_TOKEN_EXPIRE_TIME=${ACCESS_TOKEN_EXPIRE_TIME}
      - REFRESH_TOKEN_EXPIRE_TIME=${REFRESH_TOKEN_EXPIRE_TIME}
      - AIR_LIVE_RELOAD=${AIR_LIVE_RELOAD}
      - API_TITLE=${API_TITLE}
      - API_VERSION=${API_VERSION}
      - API_DESCRIPTION=${API_DESCRIPTION}
      - API_PORT=${API_PORT}
    command: air -c docker/.air.toml
    ports:
      - "3003:3003"
    stdin_open: true
    tty: true