// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteOtpCodeById(ctx context.Context, id pgtype.UUID) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserIdAndEmailByOtpCode(ctx context.Context, code string) (GetUserIdAndEmailByOtpCodeRow, error)
	InsertAuth(ctx context.Context, arg InsertAuthParams) (pgtype.UUID, error)
	InsertAuthOtpCode(ctx context.Context, arg InsertAuthOtpCodeParams) (pgtype.UUID, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (pgtype.UUID, error)
	SearchAuthByEmail(ctx context.Context, email string) (Auth, error)
	SearchUserByAuthID(ctx context.Context, authID pgtype.UUID) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
