// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	InsertAuth(ctx context.Context, arg InsertAuthParams) (pgtype.UUID, error)
	InsertAuthOtpCode(ctx context.Context, arg InsertAuthOtpCodeParams) (pgtype.UUID, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (pgtype.UUID, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
